### ISSUE TITLE
Doesn't work if there is a period in bucket name

### ISSUE THREAD

**Issue by gmxu** [kpfaulkner/azurecopy#10]
Hi, thanks for the tool!

If I have a period in my AWS bucket name, I am unable to grab the files from the bucket. I tested with two new buckets, one with and one without a period and I am unable to list or copy my files from the bucket with a period.

**Comment by kpfaulkner** [comment]
Hi

Ahh honestly never tried that, will fix that in the next release. Thanks for the info!

Ken

**Comment by OguzPastirmaci** [comment]
Hi,

Is this fixed? I have the latest release (1.4.0.7) and hitting the same issue.

**Comment by kpfaulkner** [comment]
Please try version 1.4.1 ( https://github.com/kpfaulkner/azurecopy/releases/tag/1.4.1 ) and let me know how it goes.

Sorry for the delay.

**Comment by fabianoamorim** [comment]
I could perform the list of contents from Azure now - what was wrong was the azureAccessKey and the container URL.

Now I'm actually trying to perform the copy and I get


C:\>azurecopy -i https://se.amazonaws.com/<s3bucket> -o https://<name>.blob.core.windows.net/<containerName> -azurekey %AzureAccountKey% -s3k %AWSAccessKeyID% -s3sk %AWSSecretAccessKeyID% -blobcopy -destblobtype block blobName
 -db
GetHandler start
GetHandler retrieved azurecopy.S3Handler
GetHandler start
GetHandler retrieved azurecopy.AzureHandler
Copy blob
Unable to start copying
Exception System.ArgumentException: The argument must not be empty string.
Parameter name: blobName
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpty(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.GetBlockBlobReference(String blobName, Nullable`1 snapshotTime)
   at azurecopy.AzureBlobCopyHandler.StartCopy(BasicBlobContainer origBlob, String DestinationUrl, DestinationBlobType destBlobTyp
e, Boolean skipIfExists)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnu
merable`1 origBlobList, String destinationUrl, DestinationBlobType destBlob
Type, Boolean debugMode, Boolean skipIfExists)
New Batch


Failed:
Aborted:
Pending:
Copy complete

**Comment by fabianoamorim** [comment]
How do I do to copay all files at once?

**Comment by kpfaulkner** [comment]
Hi

Unless the URLs aren’t copying/pasting correctly into the email I suspect they’re one problem.
Both the S3 and Azure URLs look wrong. Se.amazonaws.com isn’t valid (as far as I know) and .blob.core.windows.net isn’t valid either. They’d need to be something like.

S3: Mybucket.s3.amazonaws.com
Azure:  myaccount.blob.core.windows.net

In the error below, you’re listening “blobName” in the command, which doesn’t belong there.

Say, you have a S3 bucket called “mybucket” and an Azure account called “myaccount” with a container called “mycontainer” and wanted to copy all the content from S3 to Azure. The command to run would be:

azurecopy -i https://mybucket.s3.amazonaws.com/ -o https://myaccount.blob.core.windows.net/mycontainer/ -azurekey %AzureAccountKey% -s3k %AWSAccessKeyID% -s3sk %AWSSecretAccessKeyID% -blobcopy

Thanks

Ken
