### ISSUE TITLE
Spaces in file name

### ISSUE THREAD

**Issue by dpoincelot** [kpfaulkner/azurecopy#14]
Hi, When running the copy from AWS to Azure the script breaks when it hits a file name using a space. The space is replaced with a % and as a result, it looks like the command line sees that as a variable command. Any way to escape the spaces with a double percent or to strip out the spaces all together when pushing the file to Azure? Thanks!

   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.StartCopyFromBlob(Uri source, AccessCondition sourceAccessCondition, AccessCondition destAccessCondition, BlobRequestOptions options, OperationContext operationContext)
   at azurecopy.AzureBlobCopyHandler.StartCopy(String sourceUrl, String DestinationUrl, DestinationBlobType destBlobType)
   at azurecopycommand.Program.DoNormalCopy()
   at azurecopycommand.Program.Process()
   at azurecopycommand.Program.Main(String[] args)

**Comment by dpoincelot** [comment]
I compiled the 1.3.0 release and was able to get it working.

**Comment by kpfaulkner** [comment]
I'll look into it.

Ahh just saw your follow up message. Did you do a code change?

**Comment by dpoincelot** [comment]
Hi Ken,

No code change. It just worked with that 1.3 branch. I'm still getting
errors after 5 gigs or so with a duplication error. I have 25TB to move, so
it may not be possible.

Thanks,
Dan

**Comment by dpoincelot** [comment]
Hi Ken,

Here is the error I get after copying 5GB of the 25TB. Not sure if you know
what this means?

Thanks,
Dan
