### ISSUE TITLE
Sharepoint online: "The given path's format is not supported"

### ISSUE THREAD

**Issue by gabeng** [kpfaulkner/azurecopy#19]
When I try to list the contents of a sharepoint library, I get the following error:
```
azurecopy.exe -spu <username> -spp <password> -list https://<domain>.sharepoint.com/subsite/Shared%20Documents
```

```
GetHandler start
GetHandler retrieved azurecopy.FileSystemHandler
container name https:\domain\site
Unknown error generated. Please report to Github page https://github.com/kpfaulkner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag. System.NotSupportedException: The given path's format is not supported.
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path)
   at azurecopy.FileSystemHandler.<ListBlobsInContainer>d__11.MoveNext()
   at azurecopycommand.Program.DoList(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path)
   at azurecopy.FileSystemHandler.<ListBlobsInContainer>d__11.MoveNext()
   at azurecopycommand.Program.DoList(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)


```

**Comment by kpfaulkner** [comment]
I'll have a look at that when I can. Sharepoint support hasn't really been maintained properly (only a couple of people were querying about it) and that was a few years ago.

Thanks for reporting it!

Ken

**Comment by gabeng** [comment]
Hi Ken,

were you able to take a look at this? Is SP Online support functional?

Ben

**Comment by kpfaulkner** [comment]
Sorry, but for now the Sharepoint functionality will remain disabled. There are many features on the roadmap and Sharepoint isn't a highly used feature.

If you (or anyone) want to fix up the code I'm more than willing to accept pull requests that restore it.

Sorry, but there are only so many spare hours in the day to work on this and I have to draw the line somewhere.

Ken

**Comment by gabeng** [comment]
Completely understood. Keep up the good work!
