### ISSUE TITLE
Stream was too long

### ISSUE THREAD

**Issue by raphaelm22** [kpfaulkner/azurecopy#32]
```
Unknown error generated. 
Please report to Github page https://github.com/kpfaulkner/azurecopy/issues . 
Can view underlying stacktrace by adding -db flag. System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at azurecopy.S3Handler.ReadBlob(String containerName, String blobName, String cacheFilePath)
   at azurecopycommand.Program.DoNormalCopy(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at azurecopy.S3Handler.ReadBlob(String containerName, String blobName, String cacheFilePath)
   at azurecopycommand.Program.DoNormalCopy(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)
```

**Comment by kpfaulkner** [comment]
Hi

How big is the blob you're trying to copy?

Also, can you show me the exact command you're using?

Thanks

Ken

**Comment by raphaelm22** [comment]
Sorry for the poor details.

The command:
`\azurecopy.exe -db -i https://s3-sa-east-1.amazonaws.com/r*********-storage/ -o https://******.blob.core.windows.net/backup`

File size: 2.31 GB

**Comment by kpfaulkner** [comment]
Thanks...

Can you try the -blobcopy flag? This means that the blobs aren't copied to your machine first (which seems to be the issue with the large blob) but is copied directly from S3 to Azure without going through your machine.

Please let me know if that helps :)

Cheers

Ken

**Comment by raphaelm22** [comment]
I received the following message countless times:

```
Failed:
Aborted:
Pending:
/backup/Test/training.iso


Failed:
Aborted:
Pending:
/backup/Test/training.iso
```

**Comment by kpfaulkner** [comment]
Hi

But no errors?

I’d check the Azure container to see if it got copied. If the file was > 2G it might have taken a while.
Please check Azure to see if its there.

Cheers

Ken

**Comment by raphaelm22** [comment]
Hi @kpfaulkner,

The file exists, but with zero size

The quoted message is displayed repeatedly after executing the command.

**Comment by kpfaulkner** [comment]
Hi

Hmmm can you try the same command with a smaller file? (just want to confirm the mechanism is working for you in general, and then focus on size issue).
Yes, the message should repeat a lot since as Azure copies the file from S3 to itself, azurecopy will just keep polling the status of it. 

Any luck with a smaller file?

Cheers

Ken

**Comment by raphaelm22** [comment]
@kpfaulkner I'm sorry, I was so impatient at the moment that I did not notice the file was in the "Pending" queue.

That is, the solution was even to use the flag `-blobcopy`

Once again, I'm sorry for the lack of attention.
