### ISSUE TITLE
error while copying data, list is working fine.

### ISSUE THREAD

**Issue by Sonam-sunny** [kpfaulkner/azurecopy#37]
I am getting error when i am trying copy data from s3 to azure blob. but i am able to list data from both amazon s3 and azure blob. error types are 404 and 403.

**Comment by kpfaulkner** [comment]
Hi

Do you get any stacktrace at all?

Also, can you show me the exact command you used?

Thanks

Ken

**Comment by Sonam-sunny** [comment]
command-  azurecopy.exe -i "https://
s3.amazonaws.com/name/receipts" -o "C:\\Azureifcopies"  -azu
rekey %AzureAccountKey% -s3k %AWSAccessKeyID% -s3sk %AWSSecretAccessKeyID%
-blob
copy -destblobtype block


Error log-
GetHandler start
GetHandler retrieved azurecopy.S3Handler
GetHandler start
GetHandler retrieved azurecopy.FileSystemHandler
Unable to start copying receipts
Exception System.ArgumentException: The argument must not be empty string.
Parameter name: accountName
   at
Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpt
y(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String
accoun
tName, String keyValue, String keyName)
   at azurecopy.Utils.AzureHelper.GetCloudStorageAccount(String url, String
acco
untKey, String accountName)
   at azurecopy.Utils.AzureHelper.GetCloudBlobClient(String url, Boolean
isSrc,
String accountKey)
   at azurecopy.AzureBlobCopyHandler.StartCopy(BasicBlobContainer origBlob,
Stri
ng DestinationUrl, DestinationBlobType destBlobType, Boolean skipIfExists)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnumerable`1
origBlobList, S
tring destinationUrl, DestinationBlobType destBlobType, Boolean debugMode,
Boole
an skipIfExists)
New Batch
Unknown error generated. Please report to Github page
https://github.com/kpfaulk
ner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag.
Syste
m.ArgumentException: The argument must not be empty string.
Parameter name: accountName
   at
Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpt
y(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String
accoun
tName, String keyValue, String keyName)
   at azurecopy.Utils.AzureHelper.GetCloudStorageAccount(String url, String
acco
untKey, String accountName)
   at azurecopy.Utils.AzureHelper.GetCloudBlobClient(String url, Boolean
isSrc,
String accountKey)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl,
Copy
Status copyStatusFilter)
   at azurecopy.AzureBlobCopyHandler.MonitorBlobCopy(String destinationUrl)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnumerable`1
origBlobList, S
tring destinationUrl, DestinationBlobType destBlobType, Boolean debugMode,
Boole
an skipIfExists)
   at azurecopycommand.Program.DoNormalCopy(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)
   at
Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpt
y(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String
accoun
tName, String keyValue, String keyName)
   at azurecopy.Utils.AzureHelper.GetCloudStorageAccount(String url, String
acco
untKey, String accountName)
   at azurecopy.Utils.AzureHelper.GetCloudBlobClient(String url, Boolean
isSrc,
String accountKey)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl,
Copy
Status copyStatusFilter)
   at azurecopy.AzureBlobCopyHandler.MonitorBlobCopy(String destinationUrl)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnumerable`1
origBlobList, S
tring destinationUrl, DestinationBlobType destBlobType, Boolean debugMode,
Boole
an skipIfExists)
   at azurecopycommand.Program.DoNormalCopy(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)

**Comment by Sonam-sunny** [comment]
Hi Ken,

Please find the following log.\

GetHandler retrieved azurecopy.S3Handler
GetHandler start
GetHandler retrieved azurecopy.FileSystemHandler
Unable to start copying receipts
Exception System.ArgumentException: The argument must not be empty string.
Parameter name: accountName
   at
Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpt
y(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String
accoun
tName, String keyValue, String keyName)
   at azurecopy.Utils.AzureHelper.GetCloudStorageAccount(String url, String
acco
untKey, String accountName)
   at azurecopy.Utils.AzureHelper.GetCloudBlobClient(String url, Boolean
isSrc,
String accountKey)
   at azurecopy.AzureBlobCopyHandler.StartCopy(BasicBlobContainer origBlob,
Stri
ng DestinationUrl, DestinationBlobType destBlobType, Boolean skipIfExists)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnumerable`1
origBlobList, S
tring destinationUrl, DestinationBlobType destBlobType, Boolean debugMode,
Boole
an skipIfExists)
New Batch
Unknown error generated. Please report to Github page
https://github.com/kpfaulk
ner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag.
Syste
m.ArgumentException: The argument must not be empty string.
Parameter name: accountName
   at
Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpt
y(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String
accoun
tName, String keyValue, String keyName)
   at azurecopy.Utils.AzureHelper.GetCloudStorageAccount(String url, String
acco
untKey, String accountName)
   at azurecopy.Utils.AzureHelper.GetCloudBlobClient(String url, Boolean
isSrc,
String accountKey)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl,
Copy
Status copyStatusFilter)
   at azurecopy.AzureBlobCopyHandler.MonitorBlobCopy(String destinationUrl)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnumerable`1
origBlobList, S
tring destinationUrl, DestinationBlobType destBlobType, Boolean debugMode,
Boole
an skipIfExists)
   at azurecopycommand.Program.DoNormalCopy(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)
   at
Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpt
y(String paramName, String value)
   at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String
accoun
tName, String keyValue, String keyName)
   at azurecopy.Utils.AzureHelper.GetCloudStorageAccount(String url, String
acco
untKey, String accountName)
   at azurecopy.Utils.AzureHelper.GetCloudBlobClient(String url, Boolean
isSrc,
String accountKey)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl)
   at azurecopy.Utils.AzureHelper.ListBlobsInContainer(String containerUrl,
Copy
Status copyStatusFilter)
   at azurecopy.AzureBlobCopyHandler.MonitorBlobCopy(String destinationUrl)
   at azurecopy.AzureBlobCopyHandler.StartCopyList(IEnumerable`1
origBlobList, S
tring destinationUrl, DestinationBlobType destBlobType, Boolean debugMode,
Boole
an skipIfExists)
   at azurecopycommand.Program.DoNormalCopy(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)

**Comment by kpfaulkner** [comment]
Hi

The command looks wrong

azurecopy.exe -i "https://s3.amazonaws.com/name/receipts" -o "C:\\Azureifcopies"  -azurekey %AzureAccountKey% -s3k %AWSAccessKeyID% -s3sk %AWSSecretAccessKeyID% -blobcopy -destblobtype block


The key thing here is you're telling it to use "blobcopy" which can ONLY be used if the destination is Azure (sorry if that wasn't clear). So I'm thinking it's getting a bit mixed up when telling the destination is local file but also indicating Azure is a destination. If you remove -blobcopy   what are your results?

**Comment by Sonam-sunny** [comment]
actually i tried with both blob and local both i am getting same error

**Comment by kpfaulkner** [comment]
Can you provide the *exact* command you use for the Azure case (the one provided is for local filesystem). Also can you try it without -blobcopy

Thanks
