### ISSUE TITLE
The remote server returned an error: (403) 

### ISSUE THREAD

**Issue by habtamua** [kpfaulkner/azurecopy#38]
Got this error while i tried to list files from S3 storage and i already set Azure and AWS Access Key, 

```
set AzureAccountKey=MyAzureStorageAccountKey 
set AWSAccessKeyID=MyS3AccessId 
set AWSSecretAccessKeyID=MyS3SecretKey 
set AWSRegion value=us-east-1
```

`azurecopy.exe -list https://mybucket.s3-website-us-east-1.amazonaws.com  -s3k %AWSAccessKeyID% -s3sk %AWSSecretAccessKeyID%
`
_Unknown error generated. Please report to Github page https://github.com/kpfaulkner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag. Amazon.S3.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) 
Forbidden._

_at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.S3.AmazonS3Client.GetBucketLocation(GetBucketLocationRequest request)
   at azurecopy.Utils.S3Helper.GenerateS3Client(String accessKey, String secretKey, String bucketName)
   at azurecopy.S3Handler.<ListBlobsInContainer>d__25.MoveNext()
   at azurecopycommand.Program.DoList(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)_

**Comment by kpfaulkner** [comment]
Hi,

Can you tell me the version you're using (or from source?)
Also, I'm assuming you're hiding your real key value but you're really setting key and value correctly based on your S3 account?

Thanks

Ken

**Comment by habtamua** [comment]
Hi Ken,
Yes, I hide the real key value on purpose.

` .\azurecopy.exe -version
1.5.1.0
Operation took 0 ms`

**Comment by habtamua** [comment]
Just found out this tool only works on command prompt not on Powershell/Powershell ISE.

Thank you
