### ISSUE TITLE
Blobcopy not working for me

### ISSUE THREAD

**Issue by apenngrace** [kpfaulkner/azurecopy#5]
Blobcopy is not working, even though regular copy works.

I am able to list files on both my S3 and Azure account using azurecopy.  I am also able to do the "regular copy" (using my local bandwidth to download from s3 and upload to azure).  However, the `-blobcopy` option fails when I try it.  Below are two examples (first one works, second one fails, third is same as second but I added the `-db` option).  The only difference between the first and second command is the `-blobcopy` option.  

```
C:\Users\Andrew\Downloads\azurecopy-1.0.1\azurecopy-1.0.1\azurecopy>azurecopy -i https://s3.amazonaws.com/apgracedev.com.s3/DroboPhotos/P1150556.MP4 -o https://apgracedev.blob.core.windows.net/s3-data
Copying blob to https://apgracedev.blob.core.windows.net/s3-data
Operation took 234774 ms

C:\Users\Andrew\Downloads\azurecopy-1.0.1\azurecopy-1.0.1\azurecopy>azurecopy -i https://s3.amazonaws.com/apgracedev.com.s3/DroboPhotos/P1150556.MP4 -o https://apgracedev.blob.core.windows.net/s3-data -blobcopy
Unknown error generated. Please report to Github page https://github.com/kpfaulkner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag.

C:\Users\Andrew\Downloads\azurecopy-1.0.1\azurecopy-1.0.1\azurecopy>azurecopy -i https://s3.amazonaws.com/apgracedev.com.s3/DroboPhotos/P1150556.MP4 -o https://apgracedev.blob.core.windows.net/s3-data -blobcopy -db
Unknown error generated. Please report to Github page https://github.com/kpfaulkner/azurecopy/issues .  Can view underlying stacktrace by adding -db flag.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.StartCopyFromBlob(Uri source, AccessCondition sourceAccessCondition, AccessCondition destAccessCondition, BlobRequestOptions options, OperationContext operationContext)
   at azurecopy.AzureBlobCopyHandler.StartCopy(BasicBlobContainer origBlob, String DestinationUrl, DestinationBlobType destBlobType)
   at azurecopycommand.Program.DoNormalCopy()
   at azurecopycommand.Program.Process()
   at azurecopycommand.Program.Main(String[] args)
```

**Comment by kpfaulkner** [comment]
Hi Grace,

I'll look into it this morning, but I suspect it's either a URI or config problem. I'll get back to you once I'm back in front of my machine.

Thanks

Ken

**Comment by apenngrace** [comment]
Thanks

**Comment by kpfaulkner** [comment]
There *was* an error when generating filenames between S3 and Azure when using blobcopy. 
Sorry about that.

Have created release 1.0.2 which fixes this. Please let me know if you have any other issues.

Ken

**Comment by apenngrace** [comment]
Thanks!
