### ISSUE TITLE
Error Copying Large Number of Files

### ISSUE THREAD

**Issue by nightwallaby** [kpfaulkner/azurecopy#7]
Hi,

I've tried copying over the ~1.5TB worth of S3 files to an Azure target and received the debug error below. There are ~6 million files in so maybe it was too much to handle? I saw the process use up to ~4GB of memory.

If I target a much smaller virtual directory it works.

PS C:\admin\azurecopy-1.1.5\azurecopy> .\azurecopy.exe -i https://s3.amazonaws.com/media/photos/ -o https://media.blob.core.windows.net/photos -v -db -blobcopy
GetHandler start
GetHandler retrieved azurecopy.S3Handler
GetHandler start
GetHandler retrieved azurecopy.AzureHandler
Unknown error generated. Please report to Github page https://github.com/kpfaulkner/azurecopy/issues .  Can view underly
ing stacktrace by adding -db flag.
   at Amazon.Runtime.Internal.Unmarshaller.Unmarshall(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3KmsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, Response
Unmarshaller unmarshaller)
   at Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   at azurecopy.S3Handler.ListBlobsInContainer(String containerName, String blobPrefix, Boolean debug)
   at azurecopycommand.Program.GetSourceBlobList(IBlobHandler inputHandler)
   at azurecopycommand.Program.DoNormalCopy()
   at azurecopycommand.Program.Process(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)

Cheers,
Simon

**Comment by kpfaulkner** [comment]
Hi

I certainly haven't tried with volumes that large. Hmmm looking at the
stack trace you supplied its the Amazon client library that is dying when
trying to get the list of S3 blobs. The only thing I can suggest is perform
multiple copies but targeting subdirectories.

ie if you have /media/photogroup1/.... and /media/photogroup2/....   then
try 2 separate commands, one on each virtual directory.

I can investigate if there is an alternative way to get the list of blobs
(maybe I could segment it within azurecopy itself), but that may take a
little while to sort out.

Do you think performing multiple commands each targeting directories will
work for you?

Thanks

Ken

**Comment by nightwallaby** [comment]
Thank Ken.

I've been looking at the since posting the Issue. The problem I'm now
facing is that if I do something like:
  azurecopy.exe -i https://s3.amazonaws.com/media/photos/2016 -o
https://media.blob.core.windows.net/photos/2016

..I get the following stack trace:

GetHandler start
GetHandler retrieved azurecopy.S3Handler
GetHandler start
GetHandler retrieved azurecopy.AzureHandler
Unknown error generated. Please report to Github page
https://github.com/kpfaulkner/azurecopy/issues .  Can view underly
ing stacktrace by adding -db flag.
   at
Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1
cmd, IRetryPolicy policy, Opera
tionContext operationContext)
   at
Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.StartCopyFromBlob(Uri
source, AccessCondition sourceAccessCondi
tion, AccessCondition destAccessCondition, BlobRequestOptions options,
OperationContext operationContext)
   at azurecopy.AzureBlobCopyHandler.StartCopy(BasicBlobContainer origBlob,
String DestinationUrl, DestinationBlobType d
estBlobType)
   at azurecopycommand.Program.DoNormalCopy()
   at azurecopycommand.Program.Process(Boolean debugMode)
   at azurecopycommand.Program.Main(String[] args)

I think this is failing because the virtual directory destination '2016'
doesn't exist, but am continuing to test.

Cheers,
Simon

**Comment by kpfaulkner** [comment]
Hi

Try:   azurecopy.exe -i https://s3.amazonaws.com/media/photos/2016/ -o
https://media.blob.core.windows.net/photos/2016/

The trailing / is telling it that it should be considered a
directory/container etc... and should be traversed. Otherwise it thinks its
a blob.

Does that work for you?

Cheers

Ken

**Comment by nightwallaby** [comment]
Ah forgot about that S3 trailing slash, thanks.

It looks like the Azure blobcopy needs at least that first virtual
directory to already exist otherwise it fails. It seems to work fine
without specifying the blobcopy option.

Cheers,
Simon

**Comment by kpfaulkner** [comment]
Hi

Ahhh. If it's literally just that first vdir that it's having an issue with?
I think I'll need to investigate virtual directories and blobcopy flag a
bit more. See what is possible and what's problematic.

Is this a blocker for you?

Ken

**Comment by kpfaulkner** [comment]
Hi

I have a partial fix for this. It's not an issue with blobcopy but merely
how I use it for this particular scenario.
Should be able to get you a patch later tonight.

Cheers

Ken

**Comment by nightwallaby** [comment]
Great thanks Ken.

**Comment by kpfaulkner** [comment]
Hi

Have made the 1.1.6 PRE-release.
Have tested a few cases locally, all works fine for me.

In this version I can do commands such as:

azurecopy -i https://xxxx.s3.amazonaws.com/newdir/dir2/ -o
https://ddddd.blob.core.windows.net/temp/dir4/ -blobcopy

in this case "dir4" on azure doesn't exist yet. It will copy all of the
content in the dir2 vdir on S3 to the dir4 vdir on Azure.

Hope that helps.

Ken

**Comment by kpfaulkner** [comment]
Any luck?

**Comment by nightwallaby** [comment]
Sorry for the delay. Yes that has worked thanks.

**Comment by kpfaulkner** [comment]
Hi Simon,

Cool, glad to hear it!

Ken
